#
#                                                                         
/control/verbose 2
/run/verbose 1
#
/run/initialize
#
/process/list
#
# rdm is applied only to the different soil layers
/process/had/rdm/noVolumes
/process/had/rdm/selectVolume grainLV
/process/had/rdm/selectVolume boxLV
#
# place the isotopes in the middle of the target, at rest. 
#
/gun/particle ion
/gun/ion 86 222
/gun/energy 86 keV
#
/run/printProgress 100
/run/beamOn 100
